version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5433:5432"
    networks:
      - keycloak-network
    environment:
      POSTGRES_MULTIPLE_DATABASES: "MRM,superset,keycloak"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: Europe/Moscow
      LC_TIME: C
      LC_ALL: C.UTF-8
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - keycloak-network
    environment:
      TZ: Europe/Moscow
      LC_TIME: C
    volumes:
      - redisdata:/data
    command: redis-server --requirepass 123 --save 60 1 --loglevel verbose
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "123", "ping"]

  keycloak:
    build:
      context: .
      dockerfile: ./keycloak/Dockerfile.keycloak
    container_name: keycloak
    networks:
      - keycloak-network
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: password
      KC_DB_SCHEMA: public
      TZ: Europe/Moscow
      LC_TIME: C
    depends_on:
      - postgres
    volumes:
      - keycloak_data:/opt/keycloak/data  # Для сохранения данных H2
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 15

  superset:
    build: 
      context: .
      dockerfile: ./superset/Dockerfile.superset
    container_name: superset
    ports:
      - "8088:8088"
    networks:
      - keycloak-network
    environment:
      SUPERSET_CONFIG_PATH: /app/pythonpath/superset_config.py
      SUPERSET_SECRET_KEY: bVPpwHQwagtwKevHcqJVZ2qfPonDjANl # Замените на случайный ключ
      SUPERSET_ENABLE_CORS: True
      SUPERSET_ENABLE_PROXY_FIX: True
      SUPERSET_RATELIMIT_STORAGE_URI: redis://:123@redis:6379/0
      RATELIMIT_ENABLED: False
      TZ: Europe/Moscow
      LC_TIME: C
    volumes:
      - superset_home:/app/superset_home
      - ./superset/superset_config.py:/app/pythonpath/superset_config.py
    depends_on:
      - postgres
      - keycloak
    command: >
      sh -c "
        while ! pg_isready -h postgres -U postgres -d superset; do 
          sleep 1
        done
        until nc -zv keycloak 8080
        do
            echo 'Keycloak is unavailable - sleeping'
            sleep 5
        done
        pip install psycopg2-binary &&
        pip install flask-cors authlib &&
        superset fab create-admin --username admin --firstname Admin --lastname User --email admin@example.com --password admin &&
        superset db upgrade &&
        superset init &&
        /usr/bin/run-server.sh
      "

  flask:
    build:
      context: .
      dockerfile: ./flask/Dockerfile.flask
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
      DATABASE_URL: postgresql://postgres:password@postgres:5432/MRM
      REDIS_URL: redis://:123@redis:6379/0
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_REALM: myMRM
      KEYCLOAK_CLIENT_ID: flask-app
      TZ: Europe/Moscow
      LC_TIME: C
    depends_on:
      - redis
      - keycloak
      - postgres
    networks:
      - keycloak-network

  react:
    build:
      context: .
      dockerfile: ./react/Dockerfile.react
    container_name: react-app
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://flask:5000
      - REACT_APP_SUPERSET_URL=http://superset:8088
    networks:
      - keycloak-network
    depends_on:
      - flask
      - superset
    volumes:
      - ./react:/app
      - /app/node_modules


networks:
  keycloak-network:
    driver: bridge

volumes:
    postgres-data:
    redisdata:
    keycloak_data:
    superset_home: