version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5433:5432"
    networks:
      - keycloak-network
    environment:
      POSTGRES_MULTIPLE_DATABASES: "MRM,superset"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: Europe/Moscow
      LC_TIME: C
      LC_ALL: C.UTF-8
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]

  superset:
    build: 
      context: .
      dockerfile: Dockerfile.superset
    container_name: superset
    ports:
      - "8088:8088"
    networks:
      - keycloak-network
    environment:
      SUPERSET_CONFIG_PATH: /app/pythonpath/superset_config.py
      SUPERSET_SECRET_KEY: yoursecretkey # Замените на случайный ключ
      TZ: Europe/Moscow
      LC_TIME: C
    volumes:
      - superset_home:/app/superset_home
      - ./superset_config.py:/app/pythonpath/superset_config.py
    depends_on:
      - postgres
    command: >
      sh -c "
        while ! pg_isready -h postgres -U postgres -d superset; do 
          sleep 1
        done
        pip install psycopg2-binary &&
        superset fab create-admin --username admin --firstname Admin --lastname User --email admin@example.com --password admin &&
        superset db upgrade &&
        superset init &&
        /usr/bin/run-server.sh
      "

networks:
  keycloak-network:
    driver: bridge

volumes:
    postgres-data:
    superset_home: