FROM apache/superset:latest

USER root

# Устанавливаем зависимости для Debian с явным указанием netcat-openbsd
RUN apt-get update && \
    apt-get install -y \
        postgresql-client \
        netcat-openbsd && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER superset